models/Order.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "order".
 *
 * @property int $id
 * @property int $user_id Менеджер
 * @property string $name Наименование
 * @property integer $status_id Статус
 * @property string $date Дата
 * @property string $created_at
 *
 * @property Product[] $products
 * @property OrderStatus $status
 */
class Order extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => null,
                'value' => date('Y-m-d H:i:s'),
            ],
        ];
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status_id'], 'integer'],
            [['date', 'created_at', 'date_end'], 'safe'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Наименование',
            'status_id' => 'Статус',
            'date' => 'Дата',
            'date_end' => 'Дата завершение',
            'created_at' => 'Дата и время создания',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(OrderStatus::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrdersItems()
    {
        return $this->hasMany(OrdersItem::className(), ['order_id' => 'id']);
    }
}

controllers/OrdersItemController.php
<?php

namespace app\controllers;

use Yii;
use app\models\OrdersItem;
use app\models\OrdersItemSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * OrdersItemController implements the CRUD actions for OrdersItem model.
 */
class OrdersItemController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all OrdersItem models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new OrdersItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single OrdersItem model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "OrdersItem #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Edit',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new OrdersItem model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($order_id)
    {
        $request = Yii::$app->request;
        $model = new OrdersItem();
        $model->order_id = $order_id;

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Создать",
                    'forceClose'=>true,
        
                ];         
            }else{           
                return [
                    'title'=> "Создать",
                    'size' => 'normal',
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * Updates an existing OrdersItem model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Предзаказы",
                    'forceClose'=>true,
                ];    
            }else{
                 return [
                    'title'=> "Изменить",
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing OrdersItem model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

     /**
     * Delete multiple existing OrdersItem model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete()
    {        
        $request = Yii::$app->request;
        $pks = explode(',', $request->post( 'pks' )); // Array or selected records primary keys
        foreach ( $pks as $pk ) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
       
    }

    /**
     * Finds the OrdersItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return OrdersItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = OrdersItem::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/order/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\OrderStatus;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    /*[
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'id',
        'width' => '80px',
        'hAlign' => \kartik\grid\GridView::ALIGN_CENTER,
    ],*/
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'status_id',
        'value'=>'status.name',
        'filterType' => \kartik\grid\GridView::FILTER_SELECT2,
        'filterWidgetOptions' => [
            'data' => ArrayHelper::map(OrderStatus::find()->all(), 'id', 'name'),
            'pluginOptions' => [
                'allowClear' => true,
                'placeholder' => 'Выберите'
            ],
        ],
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
    ],
    [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'date_end',
         'format' => ['date', 'php:d M Y H:i:s'],
    ],
    [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'created_at',
         'format' => ['date', 'php:d M Y H:i:s'],
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'contentOptions' => ['style' => 'white-space: nowrap;'],
        'template' => '{view}{update}{delete}',
        'buttons' => [
            'delete' => function ($url, $model) {
                return Html::a('<i class="fa fa-trash text-danger" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить данную запись?'
                ]);
            },
            'print' => function ($url, $model) {
                return Html::a('<i class="fa fa-print text-info" style="font-size: 16px;"></i>', $url, [
                        'title'=>'Печать',
                        'data-pjax' => 0,
                    ])."&nbsp;";
            },
            'update' => function ($url, $model) {
                return Html::a('<i class="fa fa-pencil text-primary" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Изменить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                ])."&nbsp;";
            }
        ],
    ],

];   

views/order/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\OrderStatus;
use dosamigos\datepicker\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date_end')->widget(
        DatePicker::className(), [
            'language' => 'ru',
            'clientOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-mm-dd',
            ]
        ])
    ?> 

    <?= $form->field($model, 'status_id')->dropDownList(ArrayHelper::map(OrderStatus::find()->all(), 'id', 'name')) ?>

	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/order/_product_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'param_id',
        'value' => 'param.name'
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'count',
        'width' => 100,
        'hAlign' => \kartik\grid\GridView::ALIGN_CENTER,
        'pageSummary' => true,
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'client',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'comment',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'user_id',
        'value' => 'user.name'
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'date_cr',
        'format' => ['date', 'php:d M Y H:i:s'],
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) {
            return Url::to(['orders-item/'.$action,'id'=>$key]);
        },
        'template' => '{update}{delete}',
        'buttons' => [
            'delete' => function ($url, $model) {
                return Html::a('<i class="glyphicon glyphicon-trash text-danger" style="font-size: 16px;"></i>', $url, [
                    'role'=>'modal-remote', 'title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-confirm-title'=>'Вы уверены?',
                    'data-confirm-message'=>'Вы действительно хотите удалить данную запись?'
                ]);
            },
            'update' => function ($url, $model) {
                return Html::a('<i class="glyphicon glyphicon-pencil text-primary" style="font-size: 16px;"></i>', $url, [
                        'role'=>'modal-remote', 'title'=>'Изменить',
                        'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                        'data-request-method'=>'post',
                    ])."&nbsp;";
            }
        ],
    ],

];

views/order/_view_pdf.php
<?php

/** @var $model \app\models\Order */

use yii\widgets\DetailView;
use yii\helpers\Url;

$this->title = "Заказ №{$model->id} «{$model->name}»";

?>
<div class="header">
    <table style="width: 100%;">
        <tr>
            <td style="width: 50%;">
            </td>
            <td style="font-family: Calibri; width: 50%; font-size: 13px; line-height: 30px;">
                <p><b>ООО «КОМФОРТ»</b></p>
                <p><b>129128,Москва, ул. Малахитовая,вл.27,стр.1,Пом.35а</b></p>
                <p><b>Телефон/Факс +7(499) 390 65 55 +7 (926) 576 37 77</b></p>
                <p><b>ИНН: 7716934815/ КПП:771601001ОКПО: 36979809</b></p>
                <p><b>E-mail my-comfort@mail.ru</b></p>
            </td>
        </tr>
    </table>
</div>

<h4 style="font-family: Calibri; margin-top: 50px; text-align: center;"><?="Спецификация к заказу No{$model->id} от ".Yii::$app->formatter->asDatetime($model->created_at, 'php:d.m.Y')?></h4>
<p style="margin-bottom: 50px;">Адрес: <span style="font-weight: bold;"><?=$model->address?></span></p>

<div class="content">
    <?php $totalSum = 0; $counter = 0; foreach ($model->products as $product): ?>
    <?php
    $totalSum += $product->getSum();
    $productCommentPks = \yii\helpers\ArrayHelper::getColumn(\app\models\ProductComment::find()->where(['product_id' => $product->id])->all(), 'comment_id');
    $comments = \app\models\Comment::find()->where(['id' => $productCommentPks])->all();

    ?>

    <table style="width: 100%;">
        <tr>
            <td>
                <img src="<?=$product->imgPath?>" style="height: 700px;" alt="">
            </td>
            <td>
                <h3 style="font-family: Calibri; width: 1000px; font-weight: bold;"><?=$product->name?></h3>
                <?= DetailView::widget([
                    'model' => $product,
                    'attributes' => [
                        [
                            'attribute' => 'order_id',
                            'visible' => $product->order_id != null,
                        ],
                        [
                            'label' => 'Менеджер',
                            'attribute' => 'user.name',
                            'visible' => $product->user_id != null,
                        ],
                        [
                            'label' => 'Категория',
                            'attribute' => 'categoryParam.name',
                            'visible' => $product->category != null,
                        ],
                        [
                            'label' => 'Направление',
                            'attribute' => 'directionParam.name',
                            'visible' => $product->direction != null,
                        ],
                        [
                            'attribute' => 'height',
                            'visible' => $product->height != null,
                        ],
                        [
                            'attribute' => 'width',
                            'visible' => $product->width != null,
                        ],
                        [
                            'attribute' => 'additional_width',
                            'visible' => $product->additional_width != null,
                        ],
                        [
                            'attribute' => 'canvas_width',
                            'visible' => $product->canvas_width != null,
                        ],
                        [
                            'attribute' => 'ral',
                            'visible' => $product->ral != null,
                        ],
                        [
                            'label' => 'Метал',
                            'attribute' => 'metalParam.name',
                            'visible' => $product->metal != null,
                        ],
                        [
                            'label' => 'Замок',
                            'attribute' => 'castleParam.name',
                            'visible' => $product->castle != null,
                        ],
                        [
                            'label' => 'Ручка',
                            'attribute' => 'handleParam.name',
                            'visible' => $product->handle != null,
                        ],
                        [
                            'label' => 'Стеклопакет',
                            'attribute' => 'glassWindowParam.name',
                            'visible' => $product->glass_window != null,
                        ],
                        [
                            'label' => 'Отбойник',
                            'attribute' => 'chipperParam.name',
                            'visible' => $product->chipper != null,
                        ],
                        [
                            'label' => 'Доводчик',
                            'attribute' => 'closerParam.name',
                            'visible' => $product->closer != null,
                        ],
                        [
                            'label' => 'Фрамуга',
                            'attribute' => 'transomParam.name',
                            'visible' => $product->transom != null,
                        ],
                        [
                            'attribute' => 'delivery',
                            'visible' => $product->delivery != null,
                        ],
                        [
                            'attribute' => 'install',
                            'visible' => $product->install != null,
                        ],
                        [
                            'label' => 'Дата и время создания',
                            'attribute' => 'created_at',
                            'format' => ['date', 'php:d M Y H:i:s'],
                            'visible' => $product->created_at != null,
                        ],
                    ],
                ]) ?>
            </td>
        </tr>
    </table>
    <hr>
    <h4 style="font-family: Calibri;">Примечания</h4>
    <p style="font-family: Calibri;"><?=implode(', ', \yii\helpers\ArrayHelper::getColumn($comments, 'name'))?></p>
    <h4 style="font-family: Calibri; margin-top: 20px;">Дополнительная информация</h4>
    <p style="font-family: Calibri;"><?=$product->additional_information?></p>
    <h4 style="margin-top: 20px;">Сумма <?=$product->getSum()?>руб. (Кол-во: <?=$product->count?>, Цена: <?=$product->price?>руб.)</h4>
    <?php if($counter < count($model->products)-1): ?>
    <pagebreak>
        <?php endif; ?>
        <?php $counter++; ?>
        <?php endforeach; ?>
        <h4 style="margin-top: 40px; font-weight: bold;">ИТОГО ОБЩАЯ СТОИМОСТЬ ПО ЗАКАЗУ СОСТАВЛЯЕТ: <?=$totalSum?>руб. В том числе НДС.</h4>
</div>

views/order/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Order */

?>
<div class="order-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/order/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = "Заказы";
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="panel panel-inverse order-index">
    <div class="panel-heading">
<!--        <div class="panel-heading-btn">-->
<!--        </div>-->
        <h4 class="panel-title">Заказы</h4>
    </div>
    <div class="panel-body">
        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' =>    Html::a('Добавить <i class="fa fa-plus"></i>', ['create'],
                    ['role'=>'modal-remote','title'=> 'Добавить заказ','class'=>'btn btn-success']).'&nbsp;'.
                Html::a('<i class="fa fa-repeat"></i>', [''],
                    ['data-pjax'=>1, 'class'=>'btn btn-white', 'title'=>'Обновить']),
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
            'headingOptions' => ['style' => 'display: none;'],
            'after'=>BulkButtonWidget::widget([
            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить',
            ["bulk-delete"] ,
            [
            "class"=>"btn btn-danger btn-xs",
            'role'=>'modal-remote-bulk',
            'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
            'data-request-method'=>'post',
            'data-confirm-title'=>'Вы уверены?',
            'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'
            ]),
            ]).
            '<div class="clearfix"></div>',
            ]
            ])?>
        </div>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Order */
?>
<div class="order-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/order/view.php
<?php

use johnitvn\ajaxcrud\BulkButtonWidget;
use johnitvn\ajaxcrud\CrudAsset;
use kartik\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $searchModel app\models\ProductSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

CrudAsset::register($this);

$this->title = "Заказ «{$model->name}»";

?>

    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <h4 class="panel-title">Предзаказы</h4>
                </div>
                <div class="panel-body">
                    <div id="ajaxCrudDatatable">
                        <?=GridView::widget([
                            'id'=>'crud-datatable',
                            'dataProvider' => $dataProvider,
                            // 'filterModel' => $searchModel,
                            'pjax'=>true,
                            'columns' => require(__DIR__.'/_product_columns.php'),
                            'panelBeforeTemplate' =>    Html::a('Добавить <i class="fa fa-plus"></i>', ['/orders-item/create', 'order_id' => $model->id],
                                    ['role'=>'modal-remote','title'=> 'Добавить','class'=>'btn btn-success']).'&nbsp;'.
                                Html::a('Назад', ['/order'], ['data-pjax'=>0, 'class'=>'btn btn-white', 'title'=>'Назад']),
                            'striped' => true,
                            'condensed' => true,
                            'responsive' => true,
                            'showPageSummary' => true,
                            'panel' => [
                                'headingOptions' => ['style' => 'display: none;'],
                                'after'=>BulkButtonWidget::widget([
                                        'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Удалить',
                                            ["/orders-item/bulk-delete"] ,
                                            [
                                                "class"=>"btn btn-danger btn-xs",
                                                'role'=>'modal-remote-bulk',
                                                'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                                'data-request-method'=>'post',
                                                'data-confirm-title'=>'Вы уверены?',
                                                'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'
                                            ]),
                                    ]).
                                    '<div class="clearfix"></div>',
                            ]
                        ])?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <h4 class="panel-title">Информация о заказе</h4>
                </div>
                <div class="panel-body">
                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'id',
                            'name',
                            [
                                'attribute' => 'date',
                                'format' => ['date', 'php:d M Y H:i:s'],
                            ],
                            [
                                'attribute' => 'created_at',
                                'format' => ['date', 'php:d M Y H:i:s'],
                            ],
                        ],
                    ]) ?>
                </div>
            </div>
        </div>
    </div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    'options' => ['class' => 'fade', 'tabindex' => false],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>